### PR TITLE
Fix broken link markdown in Troubleshooting #3 section

### PR DESCRIPTION
**Pull request by mrkshields**
Problem / Solution / Result
Links in Troubleshooting #3 section display correct link text and link to url

### CODE REVIEW

**Comment by FormerLurker** [comment]
Hey, I thought I submitted a comment on this, but apparently it didn't work.  I blame my phone app :)

Anyway, I will take a look at this ASAP.  Things have been quite hectic, so I'm quite a bit behind.

Thanks for the PR!

**Comment by mrkshields** [comment]
> Hey, I thought I submitted a comment on this, but apparently it didn't work. I blame my phone app :)
> 
> Anyway, I will take a look at this ASAP. Things have been quite hectic, so I'm quite a bit behind.
> 
> Thanks for the PR!

You're welcome

**Comment by mrkshields** [comment]
bump - can you accept/merge?

**Comment by FormerLurker** [comment]
Sorry, been so so busy.  I promise I will get around to it.

**Comment by mrkshields** [comment]
> Sorry, been so so busy. I promise I will get around to it.

Promise broken

**Pull request closed without merging**
